model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: mmimdb
    losses:
    - type: logit_bce
    metrics:
    - multilabel_macro_f1
    - multilabel_micro_f1

dataset_config:
  mmimdb:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 256

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 88000

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert: bert
