model_config:
  pythia_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: vizwiz
    losses:
    - type: logit_bce
    metrics:
    - vqa_accuracy

dataset_config:
  vizwiz:
    return_info: true
    image_features:
      train:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
      val:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
      test:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2400
    num_training_steps: 24000

training:
  monitored_metric: vizwiz/vqa_accuracy
  metric_minimize: false
