model_config:
  mmf_transformer:
    transformer_base: bert-base-uncased
    backend:
      type: huggingface
      freeze: false
      params: {}
    heads:
      - type: mlp
        freeze: false
        lr_multiplier: 1.0
        hidden_size: 768
        num_labels: ${model_config.mmf_transformer.num_labels}
    modalities:
      - type: text
        key: text
        position_dim: 512
        segment_id: 0
        embedding_dim: 768
        layer_norm_eps: 1e-12
        hidden_dropout_prob: 0.1
      - type: image
        key: image
        embedding_dim: 2048
        position_dim: 1
        segment_id: 1
        layer_norm_eps: 1e-12
        hidden_dropout_prob: 0.1
        encoder:
            type: resnet152
            params:
                pretrained: true
                pool_type: avg
                num_output_features: 1
    initializer_range: 0.02
    initializer_mean: 0.0
    token_noise_std: 0.01
    token_noise_mean: 0.0
    layer_norm_weight_fill: 1.0
    random_initialize: false
    freeze_image_encoder: false
    tie_weight_to_encoder: null
    num_labels: 2
