dataset_config:
  flickr30k_retrieval:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    num_final_outputs: 4
    features:
      train:
      - flickr30k/defaults/features/detectron.lmdb
      val:
      - flickr30k/defaults/features/detectron.lmdb
      test:
      - flickr30k/defaults/features/detectron.lmdb
    annotations:
      train:
      - /checkpoint/omkar/datasets/flickr30k/all_data_final_train_2014.jsonl
      val:
      - /checkpoint/vedanuj/datasets/flickr30k/all_data_final_test_set0_2014.jsonline
      test:
      - /checkpoint/vedanuj/datasets/flickr30k/all_data_final_test_set0_2014.jsonline
    max_features: 100
    test_id_file_path: /checkpoint/vedanuj/datasets/flickr30k/cache/flickr_test_ids.npy
    hard_neg_file_path: /checkpoint/vedanuj/datasets/flickr30k/hard_negative_cleaned.pkl
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 30
