includes:
- common/defaults/configs/tasks/vqa/vizwiz.yml
# Use soft copy
task_attributes:
  vqa:
    dataset_attributes:
      vizwiz:
        use_ocr: true
        processors:
          answer_processor:
            type: soft_copy_answer
            params:
              vocab_file: vocabs/answers_vizwiz_7k.txt
              preprocessor:
                type: simple_word
                params: {}
              context_preprocessor:
                type: simple_word
                params: {}
              max_length: 50
              num_answers: 10
model_attributes:
  lorra: &lorra
    model_data_dir: ../data
    metrics:
    - type: vqa_accuracy
    losses:
    - type: logit_bce
    num_context_features: 1
    context_feature_dim: 300
    image_feature_dim: 2048
    context_max_len: 50
    classifier:
      type: logit
      params:
        img_hidden_dim: 5000
        text_hidden_dim: 300
    image_feature_embeddings:
    - modal_combine:
        type: non_linear_element_multiply
        params:
          dropout: 0
          hidden_dim: 5000
      normalization: softmax
      transform:
        type: linear
        params:
          out_dim: 1
    context_feature_embeddings:
    - modal_combine:
        type: non_linear_element_multiply
        params:
          dropout: 0
          hidden_dim: 5000
      normalization: sigmoid
      transform:
        type: linear
        params:
          out_dim: 1
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detectron/fc6/fc7_b.pkl
        weights_file: detectron/fc6/fc7_w.pkl
    - type: default
      params: {}
    context_feature_encodings:
    - type: default
      params: {}
    image_text_modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 5000
        # 300 for FastText and 50 for order vectors
        context_dim: 350
    text_embeddings:
    - type: attention
      params:
        hidden_dim: 1024
        num_layers: 1
        conv1_out: 512
        conv2_out: 2
        dropout: 0
        embedding_dim: 300
        kernel_size: 1
        padding: 0
    context_embeddings:
    - type: identity
      params:
        embedding_dim: 350
  lorra_with_glove: *lorra
optimizer_attributes:
  params:
    eps: 1.0e-08
    lr: 0.01
    weight_decay: 0
  type: Adamax
training_parameters:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 14000
    lr_ratio: 0.01
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_iterations: 24000
    batch_size: 128
    num_workers: 7
    task_size_proportional_sampling: true
    monitored_metric: vqa_accuracy
    pretrained_mapping:
      word_embedding: word_embedding
      text_embeddings: text_embeddings
      context_feature_encoders: context_feature_encoders
      context_embeddings: context_embeddings
      context_feature_embeddings_list: context_feature_embeddings_list
      image_feature_encoders: image_feature_encoders
      image_feature_embeddings_list: image_feature_embeddings_list
      image_text_multi_modal_combine_layer: image_text_multi_modal_combine_layer
    metric_minimize: false
