includes:
- ./defaults.yaml

dataset_config:
  m4c_textcaps:
    image_features:
      val:
      - open_images/detectron_fix_100/fc6/train,m4c_textvqa_ocr_en_frcn_features/train_images
      test:
      - open_images/detectron_fix_100/fc6/test,m4c_textvqa_ocr_en_frcn_features/test_images
    imdb_files:
      val:
      - imdb/m4c_textcaps/imdb_val_filtered_by_image_id.npy  # only one sample per image_id
      test:
      - imdb/m4c_textcaps/imdb_test_filtered_by_image_id.npy  # only one sample per image_id
