model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: classification
    num_labels: 3
    losses:
    - type: cross_entropy

dataset_config:
  visual_entailment:
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

evaluation:
  metrics:
  - accuracy

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  early_stop:
    criteria: visual_entailment/accuracy
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
