dataset_config:
  masked_conceptual_captions:
    data_root_dir: ../data
    image_depth_first: false
    fast_read: false
    image_features:
      train:
      - datasets/cc/features/lmdbs/cc_train.lmdb
      val:
      - datasets/cc/features/lmdbs/cc_val.lmdb
      test:
      - datasets/cc/features/lmdbs/cc_val.lmdb
    imdb_files:
      train:
      - datasets/cc/imdbs/train_all.npy
      val:
      - datasets/cc/imdbs/val.npy
      test:
      - datasets/cc/imdbs/val.npy
    features_max_len: 100
    two_sentence: true
    two_sentence_probability: -0.1
    false_caption: true
    false_caption_probability: 0.5
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 128
    return_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
